// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE532h6fcrJAdAfsMkZcDg-Gx2vM7vpb0',
    appId: '1:756443387266:web:d38e91c4d44b15de736b9b',
    messagingSenderId: '756443387266',
    projectId: 'wise-513db',
    authDomain: 'wise-513db.firebaseapp.com',
    storageBucket: 'wise-513db.firebasestorage.app',
    measurementId: 'G-8LE13JHZYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYOnGwXPl0gdt2HR1Qn8CFBl3P4LS9Xs',
    appId: '1:756443387266:android:b6e66cdc08b0214c736b9b',
    messagingSenderId: '756443387266',
    projectId: 'wise-513db',
    storageBucket: 'wise-513db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDym51LKTPH3SdQEkobaPCIcbX-P3hSHxM',
    appId: '1:756443387266:ios:be28b37c436e3cec736b9b',
    messagingSenderId: '756443387266',
    projectId: 'wise-513db',
    storageBucket: 'wise-513db.firebasestorage.app',
    iosBundleId: 'com.example.wise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDym51LKTPH3SdQEkobaPCIcbX-P3hSHxM',
    appId: '1:756443387266:ios:be28b37c436e3cec736b9b',
    messagingSenderId: '756443387266',
    projectId: 'wise-513db',
    storageBucket: 'wise-513db.firebasestorage.app',
    iosBundleId: 'com.example.wise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE532h6fcrJAdAfsMkZcDg-Gx2vM7vpb0',
    appId: '1:756443387266:web:6ccc9486b159fbe9736b9b',
    messagingSenderId: '756443387266',
    projectId: 'wise-513db',
    authDomain: 'wise-513db.firebaseapp.com',
    storageBucket: 'wise-513db.firebasestorage.app',
    measurementId: 'G-RY6JF6BY7D',
  );
}
